(require 'diminish)
(eval-after-load "projectile" '(diminish 'projectile-mode "Pr"))
(eval-after-load "abbrev" '(diminish 'abbrev-mode "Ab"))
(eval-after-load "yasnippet" '(diminish 'yas/minor-mode "Ys"))
(eval-after-load "undo-tree" '(diminish 'undo-tree-mode ""))
