(setq ispell-program-name "hunspell") 
(require 'rw-language-and-country-codes)
(require 'rw-ispell)
(require 'rw-hunspell)
(setq ispell-dictionary "en_AU_hunspell")

(setq rw-hunspell-default-dictionary "en_AU_hunspell")
(setq rw-hunspell-dicpath-list '("/usr/share/hunspell"))
(setq rw-hunspell-make-dictionary-menu t)
(setq rw-hunspell-use-rw-ispell t)
