(add-to-list 'auto-mode-alist '("\\.less$" . css-mode))

(add-hook 'css-mode-hook '(lambda ()
  (make-local-variable 'before-save-hook)
  (add-hook 'before-save-hook 'whitespace-cleanup)
  (setq indent-tabs-mode nil)
  (fci-mode)
  (highlight-80+-mode)
))

(add-hook 'coffee-mode-hook '(lambda ()
  (make-local-variable 'before-save-hook)
  (add-hook 'before-save-hook 'whitespace-cleanup)
  (setq indent-tabs-mode nil)
  (fci-mode)
  (highlight-80+-mode)
))
