- name: install zsh
  homebrew: name=zsh state=present

- name: template zsh dotfiles
  template: src="{{item}}.j2" dest="{{user_home}}.{{item}}" owner={{user_name}} mode={{600}}
  with_items:
    - zshenv
    - zshrc
    - zpreztorc

- name: checkout prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git
       dest={{preztod}}

- name: link prezto configs
  file: state=link 
        src="{{preztod}}/runcoms/{{item}}" 
        dest="{{user_home}}.{{item}}"
  with_items:
    - zlogin
    - zlogout
    - zprofile

- name: create zsh.d
  file: state=directory path={{zshd}}

- name: "make zsh {{user_name}}'s default shell"
#   user: name={{user_name}} shell="/usr/local/bin/zsh" <== Doesn't work on OSX. Needs usermod
  sudo: yes
  shell: "/usr/bin/chsh -s /usr/local/bin/zsh {{user_name}} 2>&1 | grep '^chsh:'"
  register: chsh_result
  changed_when: 'chsh_result.stdout != "chsh: no changes made"'

