- name: "files | create emacs directories"
  file: state=directory path={{item}} owner={{user_name}} mode=700
  with_items:
    - "{{emacs_dir}}"
    - "{{emacs_org}}"

- name: "files | install emacs.d"
  template: src="{{item}}" dest="{{emacs_dir}}" owner="{{user_name}}" mode="600"
  with_fileglob:
    - emacs.d/*

- name: "files | install zshrc"
  copy: src="emacs.zshrc" dest="{{zshd}}" owner="{{user_name}}" mode="600"

- name: "files | install emc script"
  copy: src="emc" dest="{{user_bin}}" owner="{{user_name}}" mode="700"
