- name: "package-deps | install emacs cocoa"
  homebrew: name=emacs install_options=cocoa

- name: "package-deps | install ispell"
  homebrew: name=ispell

- name: "package-deps | install w3m"
  homebrew: name=w3m

