- name: tap homebrew cask
  homebrew_tap: tap=phinze/cask

- name: install cask
  homebrew: name="brew-cask" 

- name: "install watch"
  homebrew: name=watch

- name: "install wget"
  homebrew: name=wget

- name: "install curl"
  homebrew: name=curl

- name: "install htop"
  homebrew: name=htop

- name: "install tree"
  homebrew: name=tree

- name: "install postgres"
  homebrew: name=postgres

- name: install chrome
  sudo: yes
  homebrew_cask: name=google-chrome

- name: install iterm2
  homebrew_cask: name=iterm2

- name: install alfred
  homebrew_cask: name=alfred
  notify: "cask alfred"

- name: install hyperdock
  homebrew_cask: name=hyperdock

- name: install contexts
  homebrew_cask: name=contexts

- name: install vmware fusion
  homebrew_cask: "name=vmware-fusion"

- name: install toggledesktop
  homebrew_cask: "name=toggldesktop"
