# Dirty dirty hax. Pity cabal-install doesn't track versions of binaries that it has installed.
- name: "install cabal-latest-version"
  template: src="cabal-latest-version" dest="{{user_bin}}" owner="{{user_name}}" mode="700"

- name: "install cabal-latest-exe"
  copy: src="cabal-latest-exe" dest="{{user_bin}}" owner="{{user_name}}" mode="700"

# You could install the haskell platform instead if you want, but you should probably be 
# sandboxing and installing deps into your userspace instead anyhow.
- name: "install cabal-install"
  homebrew: name="cabal-install"
  notify: "cabal update"
