# Dirty dirty hax. Pity cabal-install doesn't track versions of binaries that it has installed.
- name: "install cabal-latest-version"
  template: src="cabal-latest-version" dest="{{user_bin}}" owner="{{user_name}}" mode="700"

- name: "install cabal-latest-exe"
  copy: src="cabal-latest-exe" dest="{{user_bin}}" owner="{{user_name}}" mode="700"

- name: "install cabal-latest-package-list"
  copy: src="cabal-latest-package-list" dest="{{user_bin}}" owner="{{user_name}}" mode="700"

- name: "install .ghci"
  copy: src=".ghci" dest="{{user_home}}" owner="{{user_name}}" mode="600"

- name: "install .zshrc"
  template: src="haskell.zshrc" dest="{{zshd}}" owner="{{user_name}}" mode="600"

# You could install the haskell platform instead if you want, but you should probably be 
# sandboxing and installing deps into your userspace instead anyhow.
- name: "install cabal-install"
  homebrew: name="cabal-install"
  register: cabalInstallResult

- name: "cabal-update"
  shell: "{{cabal_latest_exe}} cabal-install"
  when: cabalInstallResult.changed
  register: cabalUpdateResult"
  changed_when: cabalUpdateResult.stdout != "Already up to date"

- name: "install hoogle"
  shell: "{{cabal_latest_exe}} happy && {{cabal_latest_exe}} hoogle"
  register: hoogleInstallResult
  changed_when: hoogleInstallResult.stdout != "Already up to date"
  notify: 
    - "hoogle-generate"
