#!/usr/bin/zsh

session=""

if [[ "$COLUMNS" -eq "272" ]] ; then
  session="monitor"
elif [[ "$COLUMNS" -eq "238" ]] ; then
  session="laptop"
fi

if [[ -z $session ]] ; then
  tmux
else
  tmux attach -t $session || tmux new-session -s $session
fi
